[advisories]
ignore = [
  "RUSTSEC-2024-0370", # proc-macro-error unmaintained via yew
  "RUSTSEC-2024-0436", # paste unmaintained via thirtyfour
  "RUSTSEC-2025-0141", # bincode unmaintained via yew/gloo
]
